import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import "@/styles/styles.scss"
import Provider from '@/components/Provider/Index'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Code Helper',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-BR">
      <body className={inter.className}>
        <Provider>
          {children}
        </Provider>
      </body>
    </html>
  )
}
